lptstr/winfetch

src/winfetch.ps1
Changed `disk` to display disk letter at start and a percentage at the end to be more descriptive and closer to how neofetch displays disks. Fixes #11
=> Modified Disk to be more like it is on neofetch.

src/winfetch.ps1
Change memory to show in gigabytes instead of megabytes, as it is unlikely a user will have less than 1GB of memory nowadays. Fixes #10
=> Change memory to GB instead of MB.

src/posh-winfetch.ps1
Changes the memory info style to be "used / total" and rounds it to 1 decimal place. 
```
Memory: 6GiB / 15GiB
Memory: 9.5 GiB / 15.9 GiB
```
Fixes #19
=> Change memory style

src/posh-winfetch.ps1
Uses `Get-CimInstance` to retrieve more specific information on the operating system, compared to `[Environment]::OSVersion`.
Before:
After:
Let me know if you want to use a different style.
Also, I was thinking we may want to break the `10.0.19041` into its own `Kernel` field as neofetch does, but I'm delaying that for now as I'm planning a change to the config.
=> Provide more specific OS info

README.md
as commented in #17 unless there's a new volunteer to own the powershell gallery package, it's better to remove from main readme since it will always give outdated script code.
=> Update README.md: Removed Quick Usage due outdated script

lib/config.ps1, src/posh-winfetch.ps1
Adds `motherboard`, `battery`, `local_ip` and `public_ip` info lines.
I decided to make these additions one PR as the four new info lines are quite straightforward changes, but I'm happy to break it up too.
=> Add motherboard, battery and IP information

lib/config.ps1, src/posh-winfetch.ps1
This PR has 3 parts to it:
* Update the printing method to allow info functions to display multiple lines, by returning an array of hashtables.
* Update the disk info function so that it can display multiple disks, configured by the `$ShowDisks` configuration option.
* Fix errors when using strict-mode (fixes #40)
```pwsh
```
=> Allow disk info to show multiple disks

src/posh-winfetch.ps1
Winfetch was not parsing the output from imagemagick correctly (fixes #46).
Fixes the issue with winfetch not producing the correct image, and with the black pixel in the top left corner.
Before:
After:
=> Fix image processing

lib/config.ps1, src/posh-winfetch.ps1
This is my first attempt at improving the speed of the packages info. This is done by allowing users to disable unused package managers, and checking the default installation directory for `scoop` first.
The use of `Get-Command` takes around 160ms when it fails, this is mostly unavoidable unless we manually search the path ourselves, which is why I added the configuration option.
There are some other things I may look into in the future for `scoop` such as checking environment variables or the `scoop` config.
=> Improve packages speed

winfetch.ps1
Basically the title, for now.
Using `Write-Host` has historically been considered a bad practice. It forces output on the console, doesn't allow object/string manipulation, ignores pipelines and cannot be redirected. Here are a couple links, including one by Jeffrey Snover (creator of PowerShell) himself - 
https://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful
https://pramodsingla.com/2015/11/20/powershell-do-not-use-write-host
For now, this commit doesn't do any changes, everything in the console output is the same. In fact, it adds some useful under-the-hood features, like manipulating winfetch's output, passing to pipeline (for example, to 'rainbow' (lolcat for Windows)), redirecting the output to a file using `| Out-File abc.txt` (more on this below), and use in …
=> Replace Write-Host

winfetch.ps1
This partially reverts the changes from #56 and instead uses `Write-Output`, effectively getting the best of both worlds, progressive output and the ability to easily pipe to a file or variable. I've also included the `-stripansi` option from #56.
=> Use Write-Output

winfetch.ps1
Draws the image line by line when using the `-stripansi` parameter (as discussed in #57).
=> Write image progressively when using `-stripansi`

winfetch.ps1
This PR adds the `-configpath` parameter and an environment variable `WINFETCH_CONFIG_PATH` to set an alternate config location. It also adds the `ShowDisks` and `ShowPkgs` variables as parameters.
=> Additional commandline parameters

lib/config.ps1, winfetch.ps1
Adds a parameter `-all` which will enable/display all info segments. Pretty useful if you just want all information without having to edit your config.
=> Add -all parameter

winfetch.ps1
This makes the legacy logo the default logo on Windows 7.
Likewise, it repurposes the `legacylogo` switch into the `switchlogo` switch, which, well, switches the default logo.
=> Make sane defaults for logo

winfetch.ps1
This PR introduces substantial quality improvements, with very little code change.
Highlights:
- Speed. This one just _blows ImageMagick out of the water_. Testing on an extremely high res image (12000x6000), see below:
- Image quality. Better color reproduction and sharper outlines. See below:
- And of course, zero external dependencies from now on 🚀
=> Remove ImageMagick dependency

winfetch.ps1
When use [scoop-search](https://github.com/shilangyu/scoop-search) with `Invoke-Expression (&scoop-search --hook)` in $profile as suggested in their readme, winfetch will throw errors as following.
This error might because `scoop which scoop` return no result. I'm not sure why it returns no result but this PR is an easy workaround as shown below.
```
PS C:\Users\Gzl> scoop which scoop
Not a scoop shim.
PS C:\Users\Gzl> scoop which scoop.ps1
D:\Program Files\Scoop\apps\scoop\current\bin\scoop.ps1
```
=> scoop-search compatible

winfetch.ps1
=> Show packages through winget

winfetch.ps1
We can't possibly support all package managers. Winget (official), Scoop and Choco are most reasonable defaults.
This PR adds the ability to plug custom package counts.
I'll update the Wiki page once this gets merged.
Closes #83
=> Add ability to specify custom package managers

winfetch.ps1
This also adds support for (the upcoming) Windows 11.
=> Improve Windows Logo Detection

winfetch.ps1
This PR gives PowerShell's own package management system some love.
Cold start time is very high, so this is disabled by default. (Warm starts are instantaneous.)
=> Add PS packages information

winfetch.ps1
Dark blue on black is kind of hard to read.
[](url)
If you're actually using the old powershell terminal with its default colors, it's a bit harder than that. 
When you have something like f.lux on, it can be almost illegible if you forget to shut it off for your terminal app--and if you normally don't do this, why would you? (I tried to capture this with a screenshot but the colors are getting mangled right now).
Yellow on black and yellow on blue, though, both read easily. 
Seems like an easy quality-of-life win. (Screenshots censored to remove my user and host, but I have also changed the code so that their colors are also changed from blue to yellow.)
=> Change user, host, and rowname colors to yellow for better visibility

README.md
It's funny because it's true. Winfetch was created in late 2018/2019 with Wordpad because my school had blocked Emacs/VSCode/Atom. I don't recall the reason for not using Notepad.
=> Add `made with: wordpad` badge to README

winfetch.ps1
=> Optimize battery reporting

winfetch.ps1
Added a smaller logo variant. It's called 'Microsoft', because well, 
Closes #86
=> Small logo

winfetch.ps1
Essentially a single-line change, that allows overriding the image/logo width.
Bounds are 1 to (TerminalWidth-1).
=> Allow overriding image/logo width

winfetch.ps1
This is how `neofetch` showing multiple gpus
This is how `winfetch` showing multiple gpus before this change
This is after this change
=> Fix multi gpu not on separate lines

winfetch.ps1
- Implemented a new method to find the user's actual IPv4 address using a recursive mess of .NET witchcraft that somehow ends up being much faster
- Uses a combination of C# scripts at [https://stackoverflow.com/questions/8089685/c-sharp-finding-my-machines-local-ip-address-and-not-the-vms/25553311](url) which I converted to PowerShell
- Gets all network adapters using `[System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()`
- Checks if each adapter is online, has a gateway address, and is not a loopback adapter
- Then checks if the adapter is a WiFi or Ethernet adapter using `NetworkInterfaceType`
- _Then_ iterates through each Unicast address, and checks if the address is for InterNetwork communication
- **Then** checks if the $local_ip variable has already been …
=> Implement Faster IPv4 Address Retrieval Method

winfetch.ps1
- Replaces the `Add-Type` implementation with one that uses `System.IO.DriveInfo`
- For once, my new implementation is actually shorter than the previous one
- Significantly faster on both fast and slow systems
=> Optimize info_disks

winfetch.ps1
Implements a new method of CPU usage retrieval and process counting using .NET
- Uses `[diagnostics.process]::GetProcesses()` to get all running processes
- Iterates through every process, and converts their CPU time to total CPU utilization using the logical processor count and a timespan of the current time and the processes' StartTime, and adds it to a total
- I'm not exactly sure how this works yet
- Seems to be surprisingly accurate, but hard to test to what degree though due to CPU usage being quite volatile at small timescales
- Likely accurate enough for this use case
- Might have some more room for optimization, but it is hard to tell as the tracer I use can't seem to decide what is the heaviest part of the process
- Gets the process count using the variable assigned to the …
=> New CPU Usage Retrieval and Process Counting Method

winfetch.ps1
Currently transparent pixels just show as black:
This PR replaces transparent pixels with the terminal background:
I've also added an alphathreshold option which I found was useful for refining images with a mix of alpha values. If a pixel's alpha value is below the threshold it won't be visible.
=> Support for transparent images

winfetch.ps1
- Replaces the CIM method with one that uses the registry
- Uses the keys `~MHz` and `ProcessorNameString` at `HKLM:\HARDWARE\DESCRIPTION\System\CentralProcessor\0`
- Uses `[Microsoft.Win32.RegistryKey]::OpenRemoteBaseKey('LocalMachine', $Computername).OpenSubKey("HARDWARE\DESCRIPTION\System\CentralProcessor\0")` and `GetValue()` to get the registry keys much faster than using `Get-ItemProperty`
- Currently doesn't round the frequency as rounding is slow
Speed :
- PowerShell 5:
- 11.71ms → 4.99ms
- 2.35x Faster
- PowerShell 7:
- 12.18ms → 4.23ms
- 2.88x Faster
Bottlenecked Speed:
- PowerShell 5:
- 39.25ms → 20.28ms
- 1.94x Faster
- PowerShell 7:
- 29.43ms → 15.17ms
- 1.94x Faster
=> Faster CPU Name Retrieval Method

winfetch.ps1
Due to the extensive changes to the script this required and the difficulty this would require to maintain, I strongly recommend this be merged into a new branch.
- Ported the script to PowerShell 2
- Now theoretically compatible with Windows 7
- Confirmed that it works in a VM, but it seems that a lot of the formatting and coloring that is done is not compatible with the PowerShell 2 terminal
- Required changes to almost every function
- Major Changes:
- ErrorAction `Ignore` doesn't exist, so I replaced it with `SilentlyContinue`
- Replaced `[String]::IsNullOrWhiteSpace()` with `[String]::IsNullOrEmpty()`
- Might not work in the case the config file has only white space
- `Get-CimInstance` and other CIM things were added in PowerShell 3, so they had to be replaced with their respective …
=> Port to PowerShell 2

winfetch.ps1
Running `choco list -l` on Chocolatey 2.0.0 produces the following error:
```Invalid argument -l. This argument has been removed from the list command and cannot be used.```
Removing the `-l` argument resolves the error and winfetch works properly again.
Closes #189
=> removed "-l" arg from "choco list" for Chocolatey 2.0 compatibility
